### ISSUE TITLE
chore: notify failures of execution of daily jobs in discord

### ISSUE THREAD

**Issue by richard-ramos** [vacp2p/nim-libp2p#1403]
The following github actions are executed daily, but unless we browse the `Actions` tab in the repo, we do not know whether the daily jobs encountered issues.
- `Daily amd64` - https://github.com/vacp2p/nim-libp2p/blob/master/.github/workflows/daily_amd64.yml
- `Daily i386 (Linux)` - https://github.com/vacp2p/nim-libp2p/blob/master/.github/workflows/daily_i386.yml
- `Dependencies` - https://github.com/vacp2p/nim-libp2p/blob/master/.github/workflows/dependencies.yml

To have a more visible notification of the failure of these jobs, could it be possible to send the result of these executions to a channel in Vac's discord? Ideally only the failing executions so the noise on the channel is reduced, (P2P team would then subscribe to all notifications from this channel).

**Comment by vladopajic** [comment]
can we have notifications about master branch?

**Comment by gmelodie** [comment]
Maybe sth like this?
```yaml
  notify-on-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Failure
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\": \"GitHub CI\", \"content\": \"nim-libp2p CI failed in [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
```
